%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    /Users/papanadipapanadi/Google_Drive/Tom_LAB/Experiments/Effort_Value_Association/thired_run_300s/EVAsnacks/analysis_scripts/roseta.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/06/26 19:25:31

%% Import the data
[~, ~, raw] = xlsread( [ sub_fold '/analysis_scripts/roseta.xlsx'],'Sheet1');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,3);
raw = raw(:,[1,2,4,5,6,7]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
roseta = table;

%% Allocate imported array to column variable names
roseta.Images = data(:,1);
roseta.class = data(:,2);
roseta.value = cellVectors(:,1);
roseta.Effort = data(:,3);
roseta.Order1 = data(:,4);
roseta.Order2 = data(:,5);
roseta.Order = data(:,6);

%% Clear temporary variables
clearvars data raw cellVectors;